#!/usr/bin/env node
/**
 * Language behaviour of the DSH conversation view.
 *
 * The frame is generated by the real host-side factory and executed here against
 * DOM stubs, so this covers what a browser would show: the frame boots in the
 * language the host chose, the sound toggle keeps reporting its own state after a
 * switch, and a switch never re-projects the snapshot the frame already applied
 * (which used to replay settled office events and reset the view).
 */
import assert from "node:assert/strict";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import vm from "node:vm";

const root = await mkdtemp(path.join(os.tmpdir(), "agent-live-frame-"));
const templatePath = path.join(root, "frame.html");
const modulePath = path.join(root, "frame-document.mjs");
process.env.AGENT_LIVE_DSH_FRAME_PREVIEW = templatePath;
process.env.AGENT_LIVE_DSH_FRAME_MODULE = modulePath;

const build = path.join(path.dirname(fileURLToPath(import.meta.url)), "../build.mjs");
await import(pathToFileURL(build).href);
const { default: frameDocument } = await import(pathToFileURL(modulePath).href);
const template = await readFile(templatePath, "utf8");
assert.ok(template.includes("__AGENT_LIVE_LOCALE__"), "the frame template must carry the locale placeholder");
assert.ok(template.includes("__AGENT_LIVE_CONTENT_URI__"), "the frame template must carry the content placeholder");
assert.ok(
	(await readFile(modulePath, "utf8")).includes('locale === "zh-CN"'),
	"the host-side factory must resolve the requested locale",
);

class CustomEvent {
	constructor(type, options) {
		this.type = type;
		this.detail = options?.detail;
	}
}

function createFrame(locale) {
	const posted = [];
	const errors = [];
	const elementListeners = new Map();
	const windowListeners = new Map();
	const elements = new Map();
	const counts = { logClears: 0, applied: 0, subscribed: 0 };
	const context2d = new Proxy({ measureText: () => ({ width: 4 }) }, {
		get: (target, key) => (key in target ? target[key] : () => undefined),
		set: () => true,
	});
	class Element {
		constructor(id = "") {
			this.id = id;
			this.tagName = "div";
			this.children = [];
			this.dataset = {};
			this.hidden = false;
			this.className = "";
			this.textContent = "";
			this.value = "";
			this.childNodes = [];
			this.firstChild = null;
			this.scrollTop = 0;
			this.scrollHeight = 0;
			this.offsetWidth = 0;
			this.offsetHeight = 0;
			this.width = 0;
			this.height = 0;
			this.style = { cssText: "", setProperty() {} };
			this.classList = { add() {}, remove() {}, toggle() {}, contains: () => false };
		}
		set innerHTML(value) {
			if (this.id === "log") counts.logClears += 1;
			this.html = value;
			this.children = [];
		}
		get innerHTML() {
			return this.html ?? "";
		}
		setAttribute(name, value) { this[name] = value; }
		removeAttribute() {}
		appendChild(child) { this.children.push(child); return child; }
		append(...nodes) { this.children.push(...nodes); }
		remove() {}
		focus() {}
		blur() {}
		click() {}
		getContext() { return context2d; }
		addEventListener(type, handler) {
			const key = elementListeners.get(this) ?? new Map();
			key.set(type, [...(key.get(type) ?? []), handler]);
			elementListeners.set(this, key);
		}
		removeEventListener() {}
		dispatchEvent(event) {
			for (const handler of elementListeners.get(this)?.get(event.type) ?? []) handler(event);
			return true;
		}
		querySelector(selector) { return new Element(`${this.id}${selector}`); }
		querySelectorAll() { return []; }
		getBoundingClientRect() { return { x: 0, y: 0, top: 0, left: 0, right: 800, bottom: 600, width: 800, height: 600 }; }
		get parentElement() { return this.parent ?? (this.parent = new Element("parent")); }
	}
	const documentElement = new Element("html");
	const body = new Element("body");
	const documentStub = {
		documentElement,
		body,
		head: new Element("head"),
		getElementById(id) {
			if (!elements.has(id)) elements.set(id, new Element(id));
			return elements.get(id);
		},
		createElement: (tag) => new Element(tag),
		querySelector: (selector) => new Element(selector),
		querySelectorAll: () => [],
		addEventListener(type, handler) {
			windowListeners.set(type, [...(windowListeners.get(type) ?? []), handler]);
		},
		removeEventListener() {},
		createTextNode: (text) => ({ textContent: text }),
	};
	const win = {
		document: documentStub,
		addEventListener(type, handler) {
			windowListeners.set(type, [...(windowListeners.get(type) ?? []), handler]);
		},
		removeEventListener() {},
		dispatchEvent(event) {
			for (const handler of windowListeners.get(event.type) ?? []) handler(event);
			return true;
		},
	};
	// The bundled view imports app.js synchronously, so the frame's subscribe
	// handle is wrapped as it is assigned instead of after the fact.
	let subscribeImpl;
	Object.defineProperty(win, "AgentLiveSubscribe", {
		configurable: true,
		get: () => (subscribeImpl ? wrapped : undefined),
		set(value) {
			subscribeImpl = value;
			wrapped = (listener) => {
				counts.subscribed += 1;
				return value((event) => {
					counts.applied += 1;
					listener(event);
				});
			};
		},
	});
	let wrapped;
	const parent = { postMessage: (message) => posted.push(message) };
	const context = vm.createContext({
		window: win,
		self: win,
		document: documentStub,
		parent,
		CustomEvent,
		console: { log() {}, warn() {}, info() {}, error: (...args) => errors.push(args.join(" ")) },
		setTimeout,
		clearTimeout,
		setInterval,
		clearInterval,
		queueMicrotask,
		requestAnimationFrame: () => 0,
		cancelAnimationFrame() {},
		performance: { now: () => 0 },
		fetch: async () => ({ ok: false, status: 404, json: async () => ({}) }),
		localStorage: { getItem: () => null, setItem() {}, removeItem() {} },
		location: { search: "", href: "http://localhost/", origin: "http://localhost" },
		EventSource: class {},
		URLSearchParams,
		URL,
		navigator: { userAgent: "agent-live-frame-check" },
		devicePixelRatio: 1,
	});
	const html = frameDocument(null, locale);
	const scripts = [...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map((match) => match[1]);
	assert.equal(scripts.length, 2, "the generated frame must carry the bootstrap and the bundled view");
	vm.runInContext(scripts[0], context);
	vm.runInContext(scripts[1], context);
	return {
		win, documentStub, posted, errors, counts, parent,
		label: (id) => documentStub.getElementById(id).textContent,
		click(id) {
			const node = documentStub.getElementById(id);
			for (const handler of elementListeners.get(node)?.get("click") ?? []) handler({ target: node });
		},
		send(event) {
			const message = { source: parent, data: { source: "agent-live-dsh", event } };
			for (const handler of windowListeners.get("message") ?? []) handler(message);
		},
	};
}

try {
	const frame = createFrame("zh-CN");
	// The view script boots app.js synchronously; give the host events a turn to
	// settle before asserting what the frame already applied.
	await new Promise((resolve) => setTimeout(resolve, 50));

	assert.deepEqual(frame.errors, [], "the frame must boot without errors");
	assert.equal(frame.win.OfficeContent?.preset?.id, "builtin/tech-open-office", "the frame must build the bundled fallback office");
	assert.equal(frame.documentStub.documentElement.lang, "zh-CN", "the frame must boot in the language the host asked for");
	assert.equal(frame.label("language"), "EN", "the switch must offer the other language");
	assert.equal(frame.label("mute"), "音效: 关", "the sound label must be translated at boot");
	assert.equal(frame.counts.subscribed, 1, "the office view must subscribe to the frame once");
	assert.equal(frame.counts.applied, 0, "the frame must not project anything before the host sends it");

	frame.send({ type: "snapshot", agents: [], history: [], log: [], session: { model: "fake-model", turns: 0, busy: false, cwd: "/" } });
	const appliedAfterSnapshot = frame.counts.applied;
	const clearsAfterSnapshot = frame.counts.logClears;
	assert.ok(appliedAfterSnapshot > 0, "host events must reach the office view");
	assert.ok(clearsAfterSnapshot > 0, "the applied snapshot must rebuild the office log");

	frame.click("mute");
	assert.equal(frame.label("mute"), "音效: 开", "the sound label must follow its own state");
	frame.click("language");
	assert.ok(
		frame.posted.some((message) => message.type === "locale" && message.locale === "en"),
		"switching language must ask the host to re-create the frame",
	);
	assert.equal(frame.documentStub.documentElement.lang, "en", "static labels must switch in place");
	assert.equal(frame.label("mute"), "Sound: on", "the sound label must keep its state in the new language");
	assert.equal(frame.counts.applied, appliedAfterSnapshot, "switching language must not re-project the applied snapshot");
	assert.equal(frame.counts.logClears, clearsAfterSnapshot, "switching language must not replay the office log");

	console.log("DSH frame language: boots in the host locale, switches without replaying the applied snapshot");
} finally {
	await rm(root, { recursive: true, force: true });
}
